### ISSUE TITLE
Pressing Esc on "Select connection type" menu closes it

### ISSUE THREAD

**Issue by ReFil** [zmkfirmware/zmk-studio#26]
When pressing Esc key at the select a connection type window it will close and there's no way to reopen it without refreshing the page

**Comment by petejohanson** [comment]
@ReFil Can you please try #28 ?

**Comment by ReFil** [comment]
Yep that sorted it

**Comment by ReFil** [comment]
This issue also presents on the unlock prompt

**Comment by petejohanson** [comment]
> This issue also presents on the unlock prompt

Just pushed a fix to that PR to also not allow closing that modal, if you can test again. Thanks!

**Comment by ReFil** [comment]
That seems to do the job, can hit esc all i want and it stays open
