### ISSUE TITLE
Standalone desktop application or website?

### ISSUE THREAD

**Issue by and-elf** [zmkfirmware/zmk-studio#35]
Is this supposed to be a standalone desktop application, that users install, or a website - like VIA?
I think it could be both. A desktop application for developers and a website for most (?) users. 

The zmk GitHub hooks could probably be used in the background, to build the binaries, and then supplied to the gui when the build is complete.

**Comment by petejohanson** [comment]
@and-elf We already have an app version of this available, we just haven't formalized a first "release" since this is still in alpha testing. You can grab the latest from the latest build in https://github.com/zmkfirmware/zmk-studio/actions

**Comment by and-elf** [comment]
Oh, cool!
So, I supply a patch for the layout of my keyboard (ergodash), and then I should be able to use the webapp?

**Comment by petejohanson** [comment]
> Oh, cool!
> So, I supply a patch for the layout of my keyboard (ergodash), and then I should be able to use the webapp?

Yes. But please note this is *alpha* testing stage, and using it accepts that there may be bugs still.

**Comment by and-elf** [comment]
Well, obviously. I will try and see how it works. Anyway, very good job! It will absolutely make zmk a lot more convenient, and be hopefully adopted by many OEMs currently using via.
