### ISSUE TITLE
Linux: Web USB configuration silently fails if user does not have permissions for serial device access

### ISSUE THREAD

**Issue by krikun98** [zmkfirmware/zmk-studio#41]
Serial devices on Linux are typically set up for a user group a user is not added to by default.
When trying to use Studio over USB in such a situation, it silently swallows the error and goes back to the "Select a connection type" screen.

An error message about permissions should probably pop up in this situation.

**Comment by petejohanson** [comment]
@krikun98 Can you please try the deploy preview from https://github.com/zmkfirmware/zmk-studio/pull/47 and let me know how that works for you?
