### ISSUE TITLE
Failed to connect to the chosen device

### ISSUE THREAD

**Issue by TalanVladimir** [zmkfirmware/zmk-studio#60]
Hello,

I have problem...

Problem Screen:
![image](https://github.com/user-attachments/assets/2f7bd68f-528a-4f5f-921b-1285c25222a8)

Keyboard: Corne 42

Config: https://github.com/TalanVladimir/corne-zmk-dongle

**Comment by petejohanson** [comment]
@TalanVladimir You were attempting to connect to USB? What host OS, browser, etc?

**Comment by lesshonor** [comment]
Your firmware does not appear to be configured for ZMK Studio; there is no sign of the Kconfig option in [your last set of build logs](https://github.com/TalanVladimir/corne-zmk-dongle/actions/runs/11326241283/job/31494792517#step:12:809) or `physical-layout` in [your devicetree output](https://github.com/TalanVladimir/corne-zmk-dongle/actions/runs/11326241283/job/31494792517#step:13:1). Please [review the documentation for adding ZMK Studio support](https://zmk.dev/docs/features/studio#adding-zmk-studio-support-to-a-keyboard).

**Comment by TalanVladimir** [comment]
Done, working
