### ISSUE TITLE
Create Studio feature comparison table for the ZMK docs site.

### ISSUE THREAD

**Issue by petejohanson** [zmkfirmware/zmk-studio#70]
We need to add a "Feature Table" to the Studio feature page comparing the functionality found in Studio versus non-studio keymap/config settings today, so users understand if using Studio will suffice for their needs.

**Comment by nmunnich** [comment]
This should be closed now

**Comment by petejohanson** [comment]
Available now at https://zmk.dev/docs/features/studio#capabilities

Thanks @Nick-Munnich !
