### ISSUE TITLE
About and License modals are missing UI to close them

### ISSUE THREAD

**Issue by petejohanson** [zmkfirmware/zmk-studio#8]
Both the About and License modals are missing any sort of UI for dismissing them, e.g. close or X buttons. The only way to currently dismiss them is with an Escape key press.

**Comment by gnoulk** [comment]
took a stab at it here: https://github.com/zmkfirmware/zmk-studio/pull/12

**Comment by petejohanson** [comment]
Thanks @gnoulk for the PR! Just merged #12 so closing this issue.
