### ISSUE TITLE
Unable to edit the same layer label twice in a row

### ISSUE THREAD

**Issue by petejohanson** [zmkfirmware/zmk-studio#9]
Currently, to edit the label of a layer you just already changed the label of, you need to switch away to a different layer and then back to the desired layer again before editing its label.

**Comment by gnoulk** [comment]
is this bug still open? tried to reproduce but looks like its working?

https://github.com/user-attachments/assets/b82f9b4e-a078-4ae2-acc5-200145af90e5

**Comment by petejohanson** [comment]
Closing, this should be fixed now.
